version: '3'

services:
  php:
    container_name: php_dock
    build: php/
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    container_name: nginx_dock
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html

      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - "80:80"
      
  db:
    container_name: mariadb_dock
    image: mariadb:latest
    restart: unless-stopped
    hostname: mariadb
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      # - MYSQL_DATABASE=devops_db
      - MYSQL_USER=ken
      # - MYSQL_PASSWORD=123456789
      # - MYSQL_ROOT_HOST=localhost
      # - MARIADB_ROOT_PASSWORD = 123456789
      # - "MYSQL_ROOT_HOST=%"
  pma:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - default
    expose:
      - "80"
    ports:
      - "3001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_HOSTS=http://localhost.com/phpmyadmin

# networks:
#   default:
#     external:
#       name:
#         web_network
        